name: cmake-find-highs

on: [push, pull_request]

jobs:
  master:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      # branch: [master]

    steps:
      - uses: actions/checkout@v4

      - name: Checkout HiGHS repo
        uses: actions/checkout@v4
        with:
          repository: ERGO-Code/HiGHS
          ref: master
          path: HiGHS-master

      - name: Checkout CMakeHighsFindPackage
        uses: actions/checkout@v4
        with:
          repository: galabovaa/CMakeHighsFindPackage
          ref: master
          path: CMakeHighsFindPackage-master

      - name: Create build and install dirs
        run: |
          cmake -E make_directory ${{runner.workspace}}/build-highs-master
          cmake -E make_directory ${{runner.workspace}}/install-highs-master
          cmake -E make_directory ${{runner.workspace}}/build-find-highs-master
          cmake -E make_directory ${{runner.workspace}}/install-find-highs-master

      - name: Configure CMake HiGHS
        shell: bash
        working-directory: ${{runner.workspace}}/build-highs-master
        run: |
          cmake ${{runner.workspace}}/highs-tests/HiGHS-master \
            -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}/install-highs-master

      - name: Build, ctest and install HiGHS
        working-directory: ${{runner.workspace}}/build-highs-master
        shell: bash
        run: |
          cmake --build . --parallel 
          ctest
          cmake --install .

      - name: Build and install CMakeFindHighsPackage
        working-directory: ${{runner.workspace}}/build-find-highs-master
        shell: bash
        run: |
          cmake ${{runner.workspace}}/highs-tests/CMakeHighsFindPackage-master \
            -DHIGHS_DIR=${{runner.workspace}}/install-highs-master \
            -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}/install-find-highs-master
          cmake --build . --parallel 
          cmake --install .

      - name: Test build
        working-directory: ${{runner.workspace}}/build-find-highs-master
        shell: bash
        run: |
          ./bin/main

      - name: Test install
        working-directory: ${{runner.workspace}}/install-find-highs-master
        shell: bash
        run: |
          ./bin/main