name: cmake-find-windows

on: [push, pull_request]

jobs:
  windows:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        branch: [master, latest, cmake]

    steps:
      - uses: actions/checkout@v4

      - name: Checkout HiGHS repo
        uses: actions/checkout@v4
        with:
          repository: ERGO-Code/HiGHS
          ref: ${{matrix.branch}}
          path: HiGHS-${{matrix.branch}}

      - name: Checkout CMakeHighsFindPackage
        uses: actions/checkout@v4
        with:
          repository: galabovaa/CMakeHighsFindPackage
          ref: master
          path: CMakeHighsFindPackage-master-${{matrix.branch}}

      - name: Create build and install dirs
        run: |
          mkdir ${{runner.workspace}}\\build-highs-${{matrix.branch}}
          mkdir ${{runner.workspace}}\\install-highs-${{matrix.branch}}
          mkdir ${{runner.workspace}}\\build-find-highs-${{matrix.branch}}
          mkdir ${{runner.workspace}}\\install-find-highs-${{matrix.branch}}

      - name: Configure CMake HiGHS
        working-directory: ${{runner.workspace}}\\build-highs-${{matrix.branch}}
        run: >
          cmake ${{runner.workspace}}\\highs-tests\\HiGHS-${{matrix.branch}} 
            -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}\\install-highs-${{matrix.branch}}

      - name: Build, ctest and install HiGHS
        working-directory: ${{runner.workspace}}\\build-highs-${{matrix.branch}}
        run: |
          cmake --build . --parallel --config Release
          ctest -C Release
          cmake --install .

      - name: Configure CMakeFindHighsPackage
        working-directory: ${{runner.workspace}}\\build-find-highs-${{matrix.branch}}
        run: >
          cmake ${{runner.workspace}}\\highs-tests\\CMakeHighsFindPackage-master-${{matrix.branch}} 
            -DHIGHS_DIR=${{runner.workspace}}\\install-highs-${{matrix.branch}}\\lib\\cmake\\highs 
            -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}\\install-find-highs-${{matrix.branch}}

      - name: Build and install CMakeFindHighsPackage
        working-directory: ${{runner.workspace}}\\build-find-highs-${{matrix.branch}}
        run: |
          cmake --build . --parallel  --config Release
          cmake --install .

      - name: Test build
        working-directory: ${{runner.workspace}}\\build-find-highs-${{matrix.branch}}
        shell: bash
        run: |
          ./main.exe

      - name: Test install
        working-directory: ${{runner.workspace}}\\install-find-highs-${{matrix.branch}}
        shell: bash
        run: |
          ./bin/Release/main.exe