name: cmake-find-windows-mingw

on: [push, pull_request]

jobs:
  find_i_win:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        branch: [master, latest, v1.14.0, v1.13.0, v1.12.0]

    steps:
      - uses: actions/checkout@v4

      - name: Set up MinGW
        shell: pwsh
        run: |
          choco install mingw --no-progress -y
          "C:\ProgramData\mingw64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Checkout HiGHS repo
        uses: actions/checkout@v4
        with:
          repository: ERGO-Code/HiGHS
          ref: ${{matrix.branch}}
          path: HiGHS-${{matrix.branch}}

      - name: Checkout CMakeHighsFindPackage
        uses: actions/checkout@v4
        with:
          repository: galabovaa/CMakeHighsFindPackage
          ref: master
          path: CMakeHighsFindPackage-master-${{matrix.branch}}

      - name: Create build and install dirs
        run: |
          mkdir ${{runner.workspace}}\\build-highs-${{matrix.branch}}
          mkdir ${{runner.workspace}}\\install-highs-${{matrix.branch}}
          mkdir ${{runner.workspace}}\\build-find-highs-${{matrix.branch}}
          mkdir ${{runner.workspace}}\\install-find-highs-${{matrix.branch}}

      - name: Configure CMake HiGHS
        working-directory: ${{runner.workspace}}\\build-highs-${{matrix.branch}}
        run: >-
          cmake ${{runner.workspace}}\\highs-tests\\HiGHS-${{matrix.branch}}
          -G "MinGW Makefiles"
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}\\install-highs-${{matrix.branch}}

      - name: Build, ctest and install HiGHS
        working-directory: ${{runner.workspace}}\\build-highs-${{matrix.branch}}
        run: |
          cmake --build . --parallel
          ctest
          cmake --install .

      - name: Configure CMakeFindHighsPackage
        working-directory: ${{runner.workspace}}\\build-find-highs-${{matrix.branch}}
        run: >-
          cmake ${{runner.workspace}}\\highs-tests\\CMakeHighsFindPackage-master-${{matrix.branch}}
          -G "MinGW Makefiles"
          -DCMAKE_BUILD_TYPE=Release
          -DHIGHS_DIR=${{runner.workspace}}\\install-highs-${{matrix.branch}}\\lib\\cmake\\highs
          -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}\\install-find-highs-${{matrix.branch}}

      - name: Build and install CMakeFindHighsPackage
        working-directory: ${{runner.workspace}}\\build-find-highs-${{matrix.branch}}
        run: |
          cmake --build . --parallel
          cmake --install .

      - name: Test build
        working-directory: ${{runner.workspace}}\\build-find-highs-${{matrix.branch}}
        shell: pwsh
        run: |
          $env:PATH = '${{runner.workspace}}/install-highs-${{matrix.branch}}/bin;' + $env:PATH
          echo $Env:PATH
          .\\main.exe

      - name: Test install
        working-directory: ${{runner.workspace}}\\install-find-highs-${{matrix.branch}}
        shell: pwsh
        run: |
          $env:PATH = '${{runner.workspace}}/install-highs-${{matrix.branch}}/bin;' + $env:PATH
          echo $Env:PATH
          .\\bin\\main.exe


  find_i_win_hipo:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        branch: [master, latest, v1.14.0, v1.13.0, v1.12.0]

    steps:
      - uses: actions/checkout@v4

      - name: Set up MinGW
        shell: pwsh
        run: |
          choco install mingw --no-progress -y
          "C:\ProgramData\mingw64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Checkout HiGHS repo
        uses: actions/checkout@v4
        with:
          repository: ERGO-Code/HiGHS
          ref: ${{matrix.branch}}
          path: HiGHS-${{matrix.branch}}

      - name: Checkout CMakeHighsFindPackage
        uses: actions/checkout@v4
        with:
          repository: galabovaa/CMakeHighsFindPackage
          ref: hipo
          path: CMakeHighsFindPackage-master-${{matrix.branch}}

      - name: Create build and install dirs
        run: |
          mkdir ${{runner.workspace}}\\build-highs-hipo-${{matrix.branch}}
          mkdir ${{runner.workspace}}\\install-highs-hipo-${{matrix.branch}}
          mkdir ${{runner.workspace}}\\build-find-highs-hipo-${{matrix.branch}}
          mkdir ${{runner.workspace}}\\install-find-highs-hipo-${{matrix.branch}}

      - name: Configure CMake HiGHS
        working-directory: ${{runner.workspace}}\\build-highs-hipo-${{matrix.branch}}
        run: >-
          cmake ${{runner.workspace}}\\highs-tests\\HiGHS-${{matrix.branch}}
          -G "MinGW Makefiles"
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}\\install-highs-hipo-${{matrix.branch}}
          -DHIPO=ON -DBUILD_OPENBLAS=ON

      - name: Build, ctest and install HiGHS
        working-directory: ${{runner.workspace}}\\build-highs-hipo-${{matrix.branch}}
        run: |
          cmake --build . --parallel
          cmake --install .

      - name: Configure CMakeFindHighsPackage
        working-directory: ${{runner.workspace}}\\build-find-highs-hipo-${{matrix.branch}}
        run: >-
          cmake ${{runner.workspace}}\\highs-tests\\CMakeHighsFindPackage-master-${{matrix.branch}}
          -G "MinGW Makefiles"
          -DCMAKE_BUILD_TYPE=Release
          -DHIGHS_DIR=${{runner.workspace}}\\install-highs-hipo-${{matrix.branch}}\\lib\\cmake\\highs
          -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}\\install-find-highs-hipo-${{matrix.branch}}

      - name: Build and install CMakeFindHighsPackage
        working-directory: ${{runner.workspace}}\\build-find-highs-hipo-${{matrix.branch}}
        run: |
          cmake --build . --parallel
          cmake --install .

      - name: Test build
        working-directory: ${{runner.workspace}}\\build-find-highs-hipo-${{matrix.branch}}
        shell: pwsh
        run: |
          $env:PATH = '${{runner.workspace}}/install-highs-hipo-${{matrix.branch}}/bin;' + $env:PATH
          echo $Env:PATH
          .\\main.exe

      - name: Test install
        working-directory: ${{runner.workspace}}\\install-find-highs-hipo-${{matrix.branch}}
        shell: pwsh
        run: |
          $env:PATH = '${{runner.workspace}}/install-highs-hipo-${{matrix.branch}}/bin;' + $env:PATH
          echo $Env:PATH
          .\\bin\\main.exe
