name: cmake-find-build-windows

on: [push, pull_request]

jobs:
  find_b_win:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        branch: [master, latest]

    steps:
      - uses: actions/checkout@v4

      - name: Checkout HiGHS repo
        uses: actions/checkout@v4
        with:
          repository: ERGO-Code/HiGHS
          ref: ${{matrix.branch}}
          path: HiGHS-${{matrix.branch}}-b

      - name: Checkout CMakeHighsFindPackage
        uses: actions/checkout@v4
        with:
          repository: galabovaa/CMakeHighsFindPackage
          ref: master
          path: CMakeHighsFindPackage-master-${{matrix.branch}}-b

      - name: Create build and install dirs
        run: |
          mkdir ${{runner.workspace}}\\build-highs-${{matrix.branch}}-b
          mkdir ${{runner.workspace}}\\build-find-build-${{matrix.branch}}
          mkdir ${{runner.workspace}}\\install-find-build-${{matrix.branch}}

      - name: Configure CMake HiGHS
        working-directory: ${{runner.workspace}}\\build-highs-${{matrix.branch}}-b
        run: 
          cmake ${{runner.workspace}}\\highs-tests\\HiGHS-${{matrix.branch}}-b

      - name: Build, ctest and install HiGHS
        working-directory: ${{runner.workspace}}\\build-highs-${{matrix.branch}}-b
        run: |
          cmake --build . --parallel --config Release
          ctest -C Release

      - name: Configure CMakeFindHighsPackage
        working-directory: ${{runner.workspace}}\\build-find-build-${{matrix.branch}}
        run: >-
          cmake ${{runner.workspace}}\\highs-tests\\CMakeHighsFindPackage-master-${{matrix.branch}}-b
          -DHIGHS_DIR=${{runner.workspace}}\\build-highs-${{matrix.branch}}-b 
          -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}\\install-find-build-${{matrix.branch}}

      - name: Build and install CMakeFindHighsPackage
        working-directory: ${{runner.workspace}}\\build-find-build-${{matrix.branch}}
        run: |
          cmake --build . --parallel --config Release
          cmake --install .

      - name: Test build
        working-directory: ${{runner.workspace}}\\build-find-build-${{matrix.branch}}
        run: |
          $env:PATH = '${{runner.workspace}}/build-highs-${{matrix.branch}}-b/bin/Release;' + $env:PATH
          echo $Env:PATH
          .\\Release\\main.exe

      - name: Test install
        working-directory: ${{runner.workspace}}\\install-find-build-${{matrix.branch}}
        run: |
          $env:PATH = '${{runner.workspace}}/build-highs-${{matrix.branch}}-b/bin/Release;' + $env:PATH
          echo $Env:PATH
          .\\bin\\main.exe