name: cmake-find-highs

on: [push, pull_request]

jobs:
  master:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
        branch: [master, latest]

    steps:
      - uses: actions/checkout@v4

      - name: Checkout HiGHS repo
        uses: actions/checkout@v4
        with:
          repository: ERGO-Code/HiGHS
          ref: ${{matrix.branch}}
          path: HiGHS-${{matrix.branch}}

      - name: Checkout CMakeHighsFindPackage
        uses: actions/checkout@v4
        with:
          repository: galabovaa/CMakeHighsFindPackage
          ref: master
          path: CMakeHighsFindPackage-master-${{matrix.branch}}

      - name: Create build and install dirs
        run: |
          cmake -E make_directory ${{runner.workspace}}/build-highs-${{matrix.branch}}
          cmake -E make_directory ${{runner.workspace}}/install-highs-${{matrix.branch}}
          cmake -E make_directory ${{runner.workspace}}/build-find-highs-${{matrix.branch}}

        # cmake -E make_directory ${{runner.workspace}}/install-find-highs-${{matrix.branch}}

      - name: Configure CMake HiGHS
        shell: bash
        working-directory: ${{runner.workspace}}/build-highs-${{matrix.branch}}
        run: |
          cmake ${{runner.workspace}}/highs-tests/HiGHS-${{matrix.branch}} \
            -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}/install-highs-${{matrix.branch}}

      - name: Build, ctest and install HiGHS
        working-directory: ${{runner.workspace}}/build-highs-${{matrix.branch}}
        shell: bash
        run: |
          cmake --build . --parallel 
          ctest
          cmake --install .

      # - name: Build and install CMakeFindHighsPackage
      - name: Build CMakeFindHighsPackage
        working-directory: ${{runner.workspace}}/build-find-highs-${{matrix.branch}}
        shell: bash
        run: |
          cmake ${{runner.workspace}}/highs-tests/CMakeHighsFindPackage-master-${{matrix.branch}} \
            -DHIGHS_DIR=${{runner.workspace}}/install-highs-${{matrix.branch}}/lib/cmake/highs 
          cmake --build . --parallel 

        #  cmake --install .
        # -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}/install-find-highs-${{matrix.branch}}

      - name: Test build
        working-directory: ${{runner.workspace}}/build-find-highs-${{matrix.branch}}
        shell: bash
        run: |
          ./bin/main

      # does not find highs lib, needs more cmake code in CMakeFindHighsPackage
      # - name: Test install
      #   working-directory: ${{runner.workspace}}/install-find-highs-${{matrix.branch}}
      #   shell: bash
      #   run: |
      #     ./bin/main