name: extra-unit-tests

on: [push, pull_request]

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Checkout HiGHS repo
        uses: actions/checkout@v4
        with:
          repository: ERGO-Code/HiGHS
          ref: latest
          path: ${{runner.workspace}}/HiGHS

      - name: Checkout highs-unit-tests repo
        uses: actions/checkout@v4
        with:
          repository: galabovaa/highs-unit-tests
          ref: main
          path: ${{runner.workspace}}/highs-unit-tests

      - name: HiGHS dir 
        working-directory: HiGHS
        run: |
          ls -a
          pwd

      - name: extra tests dir
        working-directory: highs-unit-tests
        run: |
          ls -a
          pwd
        
      - name: workspace dir
        working-directory: ${{runner.workspace}} 
        run: |
          ls -a
          pwd

      - name: Symlink extra tests to HiGHS
        run: |
          ls -a
          pwd 
          ln -s ${{runner.workspace}}/highs-unit-tests ${{runner.workspace}}/HiGHS/check/highs-unit-tests/


      # - name: Create Build Environment
      #   run: cmake -E make_directory ${{runner.workspace}}/build

      # - name: Configure CMake
      #   shell: bash
      #   working-directory: ${{runner.workspace}}/build
      #   run: cmake $GITHUB_WORKSPACE -DALL_TESTS=ON -DBUILD_EXTRA_UNIT_TESTS=ON

      # - name: Build
      #   working-directory: ${{runner.workspace}}/build
      #   shell: bash
      #   run: |
      #     cmake --build . --parallel 

      # - name: Test
      #   working-directory: ${{runner.workspace}}/build
      #   shell: bash
      #   # Execute tests defined by the CMake configuration.
      #   # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      #   run: ctest --parallel --timeout 300 --output-on-failure 