name: hipo-macos-gh

on: [push, pull_request]

jobs:
  hipo:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        branch: [hipo-tt]
        config: [Release, Debug]
        all_tests: [ON, OFF]

    steps:
      - uses: actions/checkout@v4

      - name: Checkout HiGHS
        uses: actions/checkout@v4
        with:
          repository: ERGO-Code/HiGHS
          ref: ${{matrix.branch}}
          path: HiGHS

      - name: Checkout GKlib
        uses: actions/checkout@v4
        with:
          repository: KarypisLab/GKlib
          ref: master
          path: GKlib

      - name: Checkout METIS
        uses: actions/checkout@v4
        with:
          repository: KarypisLab/METIS
          ref: master
          path: METIS

      - name: Create installs dir
        working-directory: ${{runner.workspace}}
        run: |
          mkdir installs
          ls

      - name: Install GKlib Release
        working-directory: GKlib
        if: ${{ matrix.config == 'Release' }}
        run: |
          cd GKlib
          make config shared=1 prefix=${{runner.workspace}}/installs
          make
          make install

      - name: Install GKlib Debug
        working-directory: GKlib
        if: ${{ matrix.config == 'Debug' }}
        run: |
          cd GKlib
          make config shared=1 prefix=${{runner.workspace}}/installs gdb=1 debug=1
          make
          make install

      - name: Install METIS Release
        if: ${{ matrix.config == "Release"}}
        run: |
          cd METIS
          make config shared=1 prefix=${{runner.workspace}}/installs
          make
          make install

      - name: Install METIS Debug
        if: ${{ matrix.config == "Debug"}}
        run: |
          cd METIS
          make config shared=1 prefix=${{runner.workspace}}/installs gdb=1 debug=1
          make
          make install

      - name: Check METIS and GKlib
        working-directory: ${{runner.workspace}}
        run: |
          cd installs
          ls
          ls lib

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        run: |
          cmake \
          -S ${{runner.workspace}}/highs-tests/HiGHS \
          -B ${{runner.workspace}}/build \
          -DHIPO=ON \
          -DMETIS_ROOT=${{runner.workspace}}/installs \
          -DGKLIB_ROOT=${{runner.workspace}}/installs \
          -DCMAKE_BUILD_TYPE=${{ matrix.config }} \
          -DALL_TESTS=${{ matrix.all_tests}}

      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake --build . --parallel

      - name: Test executable
        working-directory: ${{runner.workspace}}/build
        run: |
          ./bin/highs --solver=hipo \
          ${{runner.workspace}}/highs-tests/HiGHS/check/instances/afiro.mps

      - name: Ctest
        working-directory: ${{runner.workspace}}/build
        run: |
          ctest --parallel --timeout 300 --output-on-failure
